live_config_reload = true

[shell]
program = "/usr/bin/zsh"

[window]
decorations = "none"
opacity = 0.9
decorations_theme_variant = "dark"

[font]
normal = { family = "RobotoMono Nerd Font Mono", style = "Regular"}
bold = { family = "RobotoMono Nerd Font Mono", style = "Bold"}
italic = { family = "RobotoMono Nerd Font Mono", style = "Italic"}
bold_italic = { family = "RobotoMono Nerd Font Mono", style = "Bold Italic"}
size = 12

[bell]
duration = 0

[keyboard]
bindings = [
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "Q", mods = "Control|Shift", action = "Quit" },
]
